// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1BuiUrmVfWBDldWNdeTA3cwfbZWOJO7o',
    appId: '1:303682874060:web:170e4699b63bf1d12f3069',
    messagingSenderId: '303682874060',
    projectId: 'stock-market-lookup',
    authDomain: 'stock-market-lookup.firebaseapp.com',
    storageBucket: 'stock-market-lookup.appspot.com',
    measurementId: 'G-597CD31ZPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq1QI2LquX74hbib4mNpvjsuVSun74S9U',
    appId: '1:303682874060:android:7d2b37fb5cee4e112f3069',
    messagingSenderId: '303682874060',
    projectId: 'stock-market-lookup',
    storageBucket: 'stock-market-lookup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVoxi7um8nBDlt-IAQ4fjdFk5zrQSzX5U',
    appId: '1:303682874060:ios:d7e08eb84020b64d2f3069',
    messagingSenderId: '303682874060',
    projectId: 'stock-market-lookup',
    storageBucket: 'stock-market-lookup.appspot.com',
    iosBundleId: 'com.example.stockMarketLookup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVoxi7um8nBDlt-IAQ4fjdFk5zrQSzX5U',
    appId: '1:303682874060:ios:f6833d9558561bbe2f3069',
    messagingSenderId: '303682874060',
    projectId: 'stock-market-lookup',
    storageBucket: 'stock-market-lookup.appspot.com',
    iosBundleId: 'com.example.stockMarketLookup.RunnerTests',
  );
}
